### PR TITLE
Proj remove legacy api

### PR DESCRIPTION
**Pull request by Krakonos**
This PR removes legacy PROJ.4 API and replaces it with v6 API in a compatible manner. Solves issue #193.

### CODE REVIEW

**Comment by z3ntu** [comment]
Old Ubuntus have too old libproj, but honestly I think < 20.04 can be dropped... 

https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=libproj-dev

**Comment by Krakonos** [comment]
Yes, I'm currently working on that. I think it's reasonable to assume that 18.x and older will continue using 0.18.4 release.

**Comment by kkofler** [comment]
For any packagers reading this, here's a version that works with the 0.18.4 release:
https://src.fedoraproject.org/rpms/merkaartor/raw/f529682d49b0a8433a523bc257a9d05323c2489b/f/merkaartor-0.18.4-proj-remove-legacy-api.patch
(I ripped out the Travis parts that do not apply and massaged the `CHANGELOG` so that the hackish version parsing script does not choke on it.)

**Comment by dotlambda** [comment]
When will there be a release with these changes?

**Comment by Krakonos** [comment]
Yes, I will be tagging rc1 as soon as I'm able to merge PRs #237 #235 , as those currently block the release for OSX and Windows platforms. PR #237 is tested, I need to double check #235 on a clean system (help would be appreciated).

**Pull request merged**
