### PR TITLE
Accept use of deprecated proj_api.h

### LINKED ISSUE #179: Build broken with GDAL 3
Build fails hard on the import/export gdal code:
```
../../src/ImportExport/ImportExportGdal.cpp:114:54: error: assigning to 'OGRSFDriver *' from incompatible type 'GDALDriver *'
    poDriver = OGRSFDriverRegistrar::GetRegistrar()->GetDriverByName(pszDriverName);
../../src/ImportExport/ImportExportGdal.cpp:493:34: error: no member named 'Open' in 'OGRSFDriverRegistrar'
    poDS = OGRSFDriverRegistrar::Open( FileName.toUtf8().constData(), FALSE );
           ~~~~~~~~~~~~~~~~~~~~~~^
../../src/ImportExport/ImportExportGdal.cpp:520:34: error: no member named 'Open' in 'OGRSFDriverRegistrar'
    poDS = OGRSFDriverRegistrar::Open( "/vsimem/temp", FALSE );
```

### PR DESCRIPTION
**Pull request by z3ntu**
CC #178

### CODE REVIEW

**Comment by Krakonos** [comment]
Thanks for the contribution. Would you mind splitting this PR into two? It seems we need to apply the workaround mentioned, as it seems to affect getX and getY methods used during import (ImportExportGdal::parseGeometry()). The proj.4 fix should be safe, I've been testing this myself for quite some time too.

**Comment by Krakonos** [comment]
PS this thread indicates we should look into shapefiles using WGS84 / EPSG4326 :
https://www.mail-archive.com/search?l=gdal-dev@lists.osgeo.org&q=subject:%22%5C%5Bgdal%5C-dev%5C%5D+gdal+and+proj%22&o=newest&f=1

**Comment by z3ntu** [comment]
Done.

**Comment by pabs3** [comment]
FYI, due to the lack of a fix for this issue, Merkaartor was removed from Debian:

https://bugs.debian.org/933492

**Pull request merged**
