### PR TITLE
Document how to develop using CLion

### PR DESCRIPTION
**Pull request by KrilleGH**

### CODE REVIEW

**Comment by KrilleGH** [comment]
Hey @Krakonos, it seems you found some time for Merkaartor recently. Please, there are two simple open PR by me.

**Comment by Krakonos** [comment]
Sure. I'm not opposed, just curious: The process is a bit more complex. I recently implement rudimentary support for CMake for similar use-case (using ccls in vim to develop). The CMake does not have all the configuration options and other things, but wouldn't that be a better way to move forward? I think it is almost always good enough for development and if you're missing something specific, I'd rather find some time to implement it; in the future I'd like to transition to CMake completely.

Thoughts?

**Comment by KrilleGH** [comment]
I'm not opposed to CMake, if you want to transition then that's fine. It seems to make integration with CLion much easier.

However in the current state only the Makefile approach works properly and the PR just documents what can to be done now to use CLion nicely. They mainly support CMake at the moment, and the described process. However the next release will feature a pretty interesting Makefile integration. So the process will significantly change.

Side note: Due to Corona I found the time to undust my C++ and hack on Merkaartor, which I intended for a long time. It's actually the first time I use CLion instead of dozens of vims (without plugins, but with exctags/pss) after using PyCharm for several years and finding that an IDE does have its merits. :grinning: I was aware of things like ccls but didn't find the time to try them before I started PyCharm for a job.

**Comment by Krakonos** [comment]
I get that. Though I'd prefer to document the cmake usage straight away. I just tried with CLion and it seems to work just fine. I can load the project, build, run and debug without issues. Code navigations seems to work fine as well. Would you mind trying that out and perhaps identifying what does not work in the cmake build for you? I know of plugins, and some configurable features are not in the CMakeLists.txt. If you need to work on those, let me know and I'll add them. Otherwise it is the version string and probably a few things here and there, but all the core functionalities should be fine.

I'm glad you decided to help out and also don't mind supporting clion. A lot of my colleagues at work use it with great success.

**Comment by KrilleGH** [comment]
Trying CMake was actually the first thing I did since CLion autodetects it. The build failed very early with some error I can't remember. I can't recheck at the moment since my evaluation period expired and there's no Community Edition. I plan to buy it when I feel like hacking next time, after returning from holidays.

**Comment by Krakonos** [comment]
Hi!
I have merged updated CMake build system and will sunset the qmake system in future releases. Please review the documentation and see if you can use CLion as is with CMake, or report what issues you found out so we can fix them.

**Comment by Krakonos** [comment]
Just checked, CLion can natively open the CMake project and seems to work just fine. Additional documentation is not really necessary, as everybody using CLion likely knows what to.

**Pull request closed without merging**
