### PR TITLE
bump osc version

### PR DESCRIPTION
**Pull request by leite**
bump osc version to improve interoperability

### CODE REVIEW

**Comment by Krakonos** [comment]
Hi!

Thanks for the PR, but I'm a little hesitant to do this change. Let me ask a few questions:

1) What problem does it solve?
2) Are the file formats compatible? That is, have you actually checked if there are any incompatible changes?

Thanks!

**Comment by naoliv** [comment]
merkaartor exports an `.osc` file which JOSM can't read:



Replacing `0.3` by `0.6` in the file makes JOSM happily understand and open it (and with everything properly in place, it _seems_)

An [example](https://github.com/openstreetmap/merkaartor/files/2478635/example.zip) file where this happens.

**Comment by Krakonos** [comment]
Hi! I tried to dig into the format and it seems there are a few changes from 0.3 to 0.6 format. However, I'm having a hard time finding a full documentation of the format. I did write an email to the osmosis-dev list, in hopes they will point me into the right direction.

**Comment by Krakonos** [comment]
It's been a few months and I got no reponse on the list, nor did I find any new info. I'm merging this speculatively. Please fill out a bug report if you find any issues.

**Pull request merged**
